"""Confounding structure for regular two-level fractional designs.

A two-level effect is a *word*: a set of factor letters (the grand mean is the
empty word ``I``). Multiplying two words is the symmetric difference of their
letters, because a squared letter is the identity (``A*A = I``). The defining
relation is the group generated by the generator words; the alias of an effect
is the effect times each defining word, reduced. Resolution is the length of the
shortest defining word.

mfgQC owns this structure rather than reading it off a library: the alias list is
the regular-design special case of the general correlation-of-columns map, and
:func:`correlation_map` builds that general form so v2 non-regular designs reuse
it.
"""

from __future__ import annotations

from itertools import combinations

import numpy as np


def parse_word(s: str) -> frozenset[str]:
    """Parse a word string like ``"ABCD"`` into a set of letters. ``"I"`` is the
    identity (empty set)."""
    s = s.strip().replace(" ", "")
    if s in ("", "I", "1"):
        return frozenset()
    return frozenset(s)


def multiply(w1: frozenset[str], w2: frozenset[str]) -> frozenset[str]:
    """Word product: symmetric difference (a squared letter drops out)."""
    return w1.symmetric_difference(w2)


def word_str(word: frozenset[str], factors: list[str]) -> str:
    """Render a word in factor order; the empty word renders as ``"I"``."""
    if not word:
        return "I"
    return "".join(f for f in factors if f in word)


def defining_group(generator_words: list[frozenset[str]]) -> list[frozenset[str]]:
    """The full defining relation: the group closure of the generator words,
    including the identity. For ``p`` independent generators this has ``2^p``
    words (the products of every subset of generators)."""
    group = {frozenset()}
    for w in generator_words:
        group |= {multiply(g, w) for g in group}
    return sorted(group, key=lambda w: (len(w), sorted(w)))


def resolution(group: list[frozenset[str]]) -> int | None:
    """Length of the shortest non-identity defining word (the design resolution)."""
    lengths = [len(w) for w in group if w]
    return min(lengths) if lengths else None


def _all_effects(factors: list[str]) -> list[frozenset[str]]:
    out: list[frozenset[str]] = []
    for r in range(1, len(factors) + 1):
        out.extend(frozenset(c) for c in combinations(factors, r))
    return out


def alias_classes(factors: list[str], group: list[frozenset[str]]):
    """Partition every effect into alias classes under the defining group.

    Returns a list of ``(representative, aliases)`` where the representative is
    the lowest-order (then lexicographic) member and ``aliases`` are the other
    members. The class aliased with the grand mean (the defining words) is
    dropped: those effects are confounded with the mean, not estimable.
    """
    defining_nonidentity = {w for w in group if w}
    seen: set[frozenset[str]] = set()
    classes = []
    for eff in _all_effects(factors):
        if eff in seen:
            continue
        members = {multiply(eff, g) for g in group}
        seen |= members
        # The class equal to the defining words is confounded with the mean.
        if frozenset() in members:
            continue
        ordered = sorted(members, key=lambda w: (len(w), sorted(w)))
        rep, rest = ordered[0], ordered[1:]
        classes.append((rep, rest))
    classes.sort(key=lambda pr: (len(pr[0]), sorted(pr[0])))
    return classes


def alias_list(factors: list[str], group: list[frozenset[str]]) -> list[str]:
    """Human-readable alias list, one line per class: ``"A = BCDE"``."""
    lines = []
    for rep, rest in alias_classes(factors, group):
        rep_s = word_str(rep, factors)
        if rest:
            lines.append(rep_s + " = " + " = ".join(word_str(w, factors) for w in rest))
        else:
            lines.append(rep_s)
    return lines


def _term_column(matrix: np.ndarray, factors: list[str], term: frozenset[str]) -> np.ndarray:
    out = np.ones(matrix.shape[0])
    for f in term:
        out = out * matrix[:, factors.index(f)]
    return out


def correlation_map(matrix: np.ndarray, factors: list[str], terms: list[frozenset[str]]):
    """Correlation matrix of the model-matrix columns for ``terms``.

    The general representation of confounding: aliased columns have correlation
    +/-1. ``terms`` are words (main effects and interactions up to the fit
    order). Returns ``(names, corr)`` with ``names`` the rendered term labels.
    """
    cols = np.column_stack([_term_column(matrix, factors, t) for t in terms])
    # columns are +/-1 and centered (mean 0) for a balanced design; guard n=1.
    corr = np.corrcoef(cols, rowvar=False) if cols.shape[1] > 1 else np.array([[1.0]])
    names = [word_str(t, factors) for t in terms]
    return names, np.atleast_2d(corr)
